### ISSUE TITLE
Alarm when bike or free-slot appears

### ISSUE THREAD

**Issue by Beeki00** [otsaloma/helsinki-city-bikes#5]
It would be somewhat usefull if an alarm could be assigned to a station.

UI could be something like, press(long?) on station if there are 0 bikes or 0 free slots start to "watch" the station, if the situation changes do notification and stop watching the station. 

I see these as temporary alarms, and they should be cleared automatically in couple of hours.

**Comment by otsaloma** [comment]
In Helsinki the stations are such dense, that I don't see this being a relevant issue, but if making the app global (#4), maybe somewhere it might be. I'll consider it, but it's very low priority.

**Comment by otsaloma** [comment]
Closing all issues as helsinki-city-bikes is no longer maintained -- new things happen in pan-bikes.

Regarding the alarm, I'll change my opinion from low priority to won't happen. It would be a lot of work for little gain. But, pan-bikes does have a cover display of three stations nearest the map center, so it should be easier to check the status of a station as you don't need to go into the app itself. Hope this is of partial help.

https://github.com/otsaloma/pan-bikes
